- lib/Parser/MimeDir.php
- tests/VObject/ReaderTest.php
Fix https://github.com/fruux/sabre-vobject/issues/175.
Fix https://github.com/owncloud/contacts/issues/635.
We skip the [BOM](http://graphemica.com/FEFF) if exists.
This PR addresses only `Parser/MimeDir.php` since I don't think it is needed in `Parser/Json.php` nor (the incoming) `Parser/Xml.php`.
> Skip the BOM if exists

- lib/Component.php
- lib/Component/VCalendar.php
- lib/Component/VCard.php
- lib/Node.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/Component/VCardTest.php
This comment adds two new options to the validator:
1. PROFILE_CARDDAV
2. PROFILE_CALDAV
Passing these options will tell the validator to assume that the
vcard/icalendar object needs to be validated specifically according to
the rules of caldav/carddav.
For vCards specifically this means that the UID is required for CardDAV,
but we only emit a warning without PROFILE_CARDDAV.
For iCalendar there's a bunch of new rules that we will eventually
integrate into sabredav.
This fixes #176.
> Validator upgrades.

- lib/Sabre/VObject/Property.php
- tests/Sabre/VObject/Property/CompoundTest.php
- tests/Sabre/VObject/PropertyTest.php
This is a fresh version of my previous pull requests #66 and #81. It fixes the wrong double-escaping of compound properties with commas and semicolons for the 2.1 branch of vobject. This is a proposed fix for issue #94.
> Fix double-escaping of , and ; in compound properties

- lib/Recur/EventIterator.php
- tests/VObject/Recur/EventIterator/ExpandFloatingTimesTest.php
to correctly expand with reference timezone (if any).
This fixes a problem where recurrent events with floating times would get set to UTC by EventIterator::getEventObject() while it should be transferred to UTC in VCalendar::expand().
> Keep floating time on Recur\EventIterator::getEventObject

- lib/Component/Available.php
- lib/Component/VAlarm.php
- lib/Component/VAvailability.php
- lib/Component/VCalendar.php
- lib/Component/VCard.php
- lib/Component/VEvent.php
- lib/Component/VFreeBusy.php
- lib/Component/VJournal.php
- lib/Component/VTimeZone.php
- lib/Component/VTodo.php
- tests/VObject/Component/VAlarmTest.php
- tests/VObject/Component/VAvailabilityTest.php
Fix https://github.com/fruux/sabre-vobject/issues/109.
[RFC Calendar Availability draft-daboo-calendar-availability-05](https://tools.ietf.org/html/draft-daboo-calendar-availability-05).
Things to check:
* `VTIMEZONE` when having `DATE-TIME` values.
> Support VAVAILABILITY, parsing

- lib/Component/VCard.php
- lib/DateTimeParser.php
- lib/Parameter.php
- lib/Parser/XML.php
- lib/Property.php
- lib/Property/ICalendar/Recur.php
- lib/Property/Text.php
- lib/Property/Uri.php
- lib/Property/VCard/DateAndOrTime.php
- lib/Property/VCard/TimeStamp.php
- lib/Writer.php
- resources/schema/xcard.rng
- tests/VObject/DateTimeParserTest.php
- tests/VObject/JCardTest.php
- tests/VObject/Parser/JsonTest.php
- tests/VObject/Parser/XmlTest.php
- tests/VObject/ReaderTest.php
- tests/VObject/WriterTest.php
Fix #167.
[RFC6351](https://tools.ietf.org/html/rfc6351):
> Implement xCard support

- lib/DateTimeParser.php
- tests/VObject/DateTimeParserTest.php
We came across some cards (generated by an export on mailbox.org) that had milliseconds in a property-value (REV in this instance), for example:
```
BEGIN:VCARD
VERSION:3.0
PRODID:OPEN-XCHANGE
FN:Armin Hackmann
N:Hackmann;Armin;;;
X-OPEN-XCHANGE-CTYPE:contact
REV:20140905T151124.056Z
UID:d91b949e-69ef-41a8-a1c3-ff6a7743973c
END:VCARD
```
If we'd want to convert a card containing this to another version, the DateTimeParser would exit with an InvalidArgumentException. While the behavior is correct (according to the spec, there shouldn't be a property-value containing milliseconds), I wonder if we should support parsing such a date-time/time value?
> milliseconds in date time parser

- lib/FreeBusyGenerator.php
- tests/VObject/FreeBusyGeneratorTest.php
The same issue that caused NoInstancesException exceptions thrown elsewhere also existed in the FreeBusy Generator.
> Fixes issue with #168 in Free/Busy Generator

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Had this RRULE case, essentially "all but the last thursday in the
month"
RRULE:FREQ=MONTHLY;BYDAY=-2TH,-3TH,-4TH,-5TH
> Fix BYDAY=-5TH

- lib/Property/ICalendar/DateTime.php
- tests/VObject/Property/ICalendar/DateTimeTest.php
When a DateTime object is created from a Unix timestamp using the @ syntax, `new \DateTime('@123456789')`, the resulting object gets a timezone with the name `+00:00` (tested with PHP 5.5.25 and 5.4.38). Passing a timezone object as the second argument does not change this.
This timezone represents UTC, but it is not identified as a UTC timezone in VObject\Property\ICalendar\DateTime.
This PR adds `+00:00` to the list of known aliases for UTC.
(BTW, there are [other aliases](http://php.net/manual/en/timezones.others.php), but they are all deprecated)
> Identify "+00:00" as UTC

- CHANGELOG.md
- bin/bench_manipulatevcard.php
- lib/Component.php
- lib/Node.php
- lib/Property.php
- tests/VObject/DocumentTest.php
- tests/VObject/Property/ICalendar/RecurTest.php
- tests/VObject/Property/TextTest.php
vobject documents stay in PHP's memory, even after they are no longer used. This is because there's a lot of circular references, which _can_ be resolved by calling `gc_collect_cycles()`, but this is not optimal.
This PR adds a `destroy()` method to all documents, components, etc, which allows a user to simply indicate that they no longer intend to use the object. This method breaks all circular references, which allows PHP to clean up the object.
While this might not be useful everywhere, this can cause massive memory savings in cases where a lot of objects are manipulated.
> Added a garbage collector.

- .travis.yml
- lib/Component/VCalendar.php
- lib/Component/VCard.php
- lib/Property/FloatValue.php
- lib/Property/IntegerValue.php
- lib/Recur/RRuleIterator.php
- tests/VObject/Property/FloatTest.php
In this PR i'll make sure that both HHVM and PHP7 are supported. HHVM was supported before, but broken as of a little while due to a php incompatibility.
PHP7 no longer allows keywords such as Integer and Float to be used as classnames, so we're renaming those.
> PHP 7 and HHVM  support

- lib/Component/VEvent.php
- lib/Recur/EventIterator.php
- tests/VObject/Component/VEventTest.php
Recurring all-day events are incorrectly included in time range requests when not using UTC in the time range.
e.g. (also see added unit test)
* All day event on every 1st of the month
* `isInTimeRange()` for the 2nd of a month 'Europe\Berlin`
* event would pass the test
This PR fixes that issue and a typo on initialization of `\Recur\EventIterator()`.
> Fix for isInTimeRange for recurring all day events in timezone

- CHANGELOG.md
- lib/BirthdayCalendarGenerator.php
- tests/VObject/BirthdayCalendarGeneratorTest.php
Instead of failing on `FN->getValue()` we're now skipping cards that don't have a FN.
> Skip cards without FN in BirthdayCalendarGenerator

- lib/Component/VCalendar.php
- lib/Recur/RDateIterator.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/RDateIteratorTest.php
VCalendar::expand ignores RDATE. Fixed that. Additionally, fixed timezone issue in RDateIterator.
> Fix rdate in vcalendar

- CHANGELOG.md
- lib/Component/VCalendar.php
- lib/InvalidDataException.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/Recur/EventIterator/ByMonthInDailyTest.php
- tests/VObject/Recur/EventIterator/BySetPosHangTest.php
- tests/VObject/Recur/EventIterator/ExpandFloatingTimesTest.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/EventIterator/IncorrectExpandTest.php
- tests/VObject/Recur/EventIterator/MissingOverriddenTest.php
- tests/VObject/Recur/EventIterator/OverrideFirstEventTest.php
It no longer edits itself in-place, which was not always a good idea.
This is BC breaking.
We also introduced a new InvalidData exception. We'll be switching to
that new exception everywhere we used generic PHP exceptions before.
Fixes #240.
> VCalendar::expand now returns an expanded version of itself.

- CHANGELOG.md
- lib/Parser/MimeDir.php
- tests/VObject/Parser/MimeDirTest.php
This PR allows a user to specify before encoding that the (vcard/icalendar) input data is not in UTF-8, so the parser can automatically decode it.
It also adds support for the `ENCODING` parameter in vCard 2.1.
Fixes #41 
Closes #43
> Support for encodings other than UTF-8.

- lib/Component/VCalendar.php
Fix https://github.com/fruux/sabre-vobject/issues/278.
The issue is that the `stripTimezones` closure is recursive but the
“self” is not defined. This way it works.
Minimal Working Example:
$a = function ($i) use (&$a) {
var_dump($i);
if ($i < 10) {
$a($i + 1);
}
};
Here we can re-use “self” (`$a`) inside the closure because it is closed
into the same lexical scope thanks to `use (&$a)`.
> VCalendar: Fix timezones stripping

- lib/DateTimeParser.php
- tests/VObject/DateTimeParserTest.php
DateTimeParser fails for syntactically correct, but invalid datetimes with a generic PHP exception instead of InvalidDataException.
This e.g. causes sabre-dav's CalDAV plugin to fail with 500 Internal Server error for such datetimes, instead of rejecting the erroneous iCalendar payload.
For example, a datetime in the 25th hour of the day passes the regex validation but fails with \Exception
DateTimeImmutable::__construct(): Failed to parse time string (2010-03-16 25:14:05) at position 11
Similarly, a date in the 13th month fails with
DateTimeImmutable::__construct(): Failed to parse time string (2010-13-31) at position 6
This change fixes both and adds unit tests.
> Throw InvalidDataException if DateTimeImmutable constructor fails

- lib/Recur/EventIterator.php
- tests/VObject/Recur/EventIterator/SameDateForRecurringEventsTest.php
If ```Sabre\VObject\Recur\EventIterator``` takes on input list os recurring events with same date start. In ```EventIterator::rewind``` generate overridden events index by timestamp of date start(```EventIterator::$overriddenEventsIndex```). So index offset will be rewritten by last event with same date start. 
Fix issue: #331
> Fix #330: Fixed case when overridden recurring events have same start date.

- bin/fetch_windows_zones.php
justed noticed because https://github.com/fruux/sabre-vobject/commit/b03193a7d32d18b2b56a1a1c222906ea58c8e016 contains a "oudated" copyright year in the generated file.
> fixed copyright info in timezone generator

- lib/Recur/EventIterator.php
- tests/VObject/Component/VEventTest.php
- tests/VObject/Recur/EventIterator/MainTest.php
Before this fix, when called with a recurring allDay event and a datetime at
midnight this method returned the instance that finish just before the
given datetime if this instance has this datetime for end.
> ISSUE 351 - fix EventIteratorFastForward

- .travis.yml
travis updates composer within the build to 1.3.x which contains a native workaround for xdebug problems.
> dont disable xdebug manually anymore in travis builds.

- lib/timezonedata/exchangezones.php
As the tilt says, it adds _Pacific Time (US & Canada)_ as exchange timezone.
> Add Pacific Time (US & Canada) as exchange timezone

- lib/Component/VCard.php
- tests/VObject/Component/VCardTest.php
see https://github.com/nextcloud/contacts/issues/206
> Added VCard without FN fallback

- lib/ITip/Broker.php
- tests/VObject/ITip/BrokerSignificantChangesTest.php
Fixes part of #126.
Ignores insignificant changes in RRULE. E.g. ignores INTERVAL=1 and order of items.
> Improve significant change detection in RRULE to limit false positives

- lib/timezonedata/php-bc.php
Discovered in Fedora QA since tzdata 2017c
https://apps.fedoraproject.org/koschei/package/php-sabre-vobject4?collection=f28
```
There was 1 error:
1) Sabre\VObject\TimeZoneUtilTest::testTimeZoneBCIdentifiers with data set #52 ('Canada/East-Saskatchewan')
Exception: DateTimeZone::__construct(): Unknown or bad timezone (Canada/East-Saskatchewan)
/builddir/build/BUILD/vobject-df9916813d1d83e4f761c4cba13361ee74196fac/tests/VObject/TimeZoneUtilTest.php:181
```
Also see http://git.php.net/?p=php-src.git;a=commitdiff;h=b2dfcb30eb7de65fbb0e86d5fc79419c8851c005
> Canada/East-Saskatchewan removed in 2017.3

- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Property/Text.php
explcitly use full qualified function calls so PHP can generate faster opcodes and doesn't need to check the local namespace for equal named functions before using the native function.
applied the changes only in the HOT path.
> use full qualified function calls in Property/Text->serialize()

- lib/Property.php
- lib/Property/Text.php
- tests/VObject/PropertyTest.php
thanks to @bwoebi for the regex (I had to adjust it to add a space before each line).
In my case it is much faster:
> use preg_replace instead of mb_strcut

- lib/ITip/Broker.php
If DTSTART and/or DTEND and other times are specified with a TZID, some clients
may fail reading the generated iCal data, since the VTIMEZONE definition is
missing.
> Broker: add timezone to CANCEL messages

- lib/Property.php
- tests/VObject/PropertyTest.php
Follow up of
#415
Repairs vCards in V3 that have a BASE64 encoding.
> Repairing BASE64 encoded vCard version 3

- lib/Component/VCalendar.php
- lib/FreeBusyGenerator.php
- lib/Parameter.php
- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Reader.php
- lib/Recur/EventIterator.php
- lib/Splitter/ICalendar.php
- lib/Splitter/SplitterInterface.php
- lib/Splitter/VCard.php
Fix minor typos throughout docstrings.
> docs: Fix typos of it's ▶︎ its, where appropriate.

- CHANGELOG.md
- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Property/VCard/DateAndOrTime.php
- lib/Version.php
It's about time to do a real release - long time is gone since the alpha1.
(And I need a release for ownCloud ;-) )
> Release 4.2.0

- lib/Parser/MimeDir.php
- tests/VObject/Splitter/VCardTest.php
When parsing a vcard file, I've got this [error](https://sentry.io/share/issue/ff63a781a8184391bf127a5a7f90a46f/):
```
Argument 3 passed to Sabre\VObject\Component::__construct() must be of the type array, string given
#40 /vendor/sabre/vobject/lib/Component.php(53): Sabre\VObject\Component::__construct
#39 [internal](0): call_user_func_array
#38 /vendor/sabre/vobject/lib/Document.php(105): Sabre\VObject\Document::__construct
#37 /vendor/sabre/vobject/lib/Document.php(175): Sabre\VObject\Document::createComponent
#36 /vendor/sabre/vobject/lib/Parser/MimeDir.php(208): Sabre\VObject\Parser\MimeDir::parseLine
#35 /vendor/sabre/vobject/lib/Parser/MimeDir.php(181): Sabre\VObject\Parser\MimeDir::parseDocument
#34 /vendor/sabre/vobject/lib/Parser/MimeDir.php(89): …
```
> Preventing creating a component for a root document

- lib/Parser/MimeDir.php
- tests/VObject/Splitter/VCardTest.php
When using option Forgiving, if a quoted printable line ends with an equal sign, followed by en empty line, there will be a parse error.
In this case, the `readLine` must not be called again.
> Fix parse with option Forgiving with trailing equal

- lib/Component/VCalendar.php
I‘ve found a bug. The creation of the new EventIterator must have the reference timezone on the third position. But ist was submitted at the second. I’ve added a null to the second position an now it works.
Could you pull these changes please?
> fixed typo in VCalendar which resulting in usage of the wrong TimeZone

- tests/VObject/Parser/MimeDirTest.php
With 7.4.0RC3
```
There was 1 error:
1) Sabre\VObject\Parser\MimeDirTest::testParseError
fgets(): read of 8192 bytes failed with errno=9 Bad file descriptor
```
This minimal fix open file in read/write mode, to avoid the new warning.
A better fix will be to detect if the stream is properly open for read in setInput 
```
is_resource 
get_resource_type == "stream"
stream_get_meta_data => "mode"
``` 
But this will be a new feature, so far away for the goal of this simple fix.
> fix  Bad file descriptor (7.4)

- .travis.yml
I think it would be better if phpstan is always ran for every php version.
> Always run phpstan in travis

- lib/Component/VCard.php
- lib/Property/VCard/PhoneNumber.php
- lib/VCardConverter.php
- tests/VObject/Property/VCard/PhoneNumberTest.php
- tests/VObject/VCardConverterTest.php
In vCard 3.0, `TEL` value should be of type `PHONE-NUMBER` ([Section 2.4.3](https://tools.ietf.org/html/rfc2426#section-2.4.3) / [Section 3.3.1](https://tools.ietf.org/html/rfc2426#section-3.3.1)).
So the following _should_ be a valid vCard:
```
BEGIN:VCARD
VERSION:3.0
TEL;TYPE=HOME;VALUE=PHONE-NUMBER:+123456789
END:VCARD
```
vObject currently throws an Exception when trying to parse that.
This PR adds the value type, and also throws it out when converting to vCard 4 (which expects `URI` type).
> Add PHONE-NUMBER value type (used for TEL in vCard 3.0)

- CHANGELOG.md
- lib/Version.php
closes https://github.com/sabre-io/vobject/issues/489
> Release 4.2.2

- .gitignore
- .php_cs.dist
- .travis.yml
- composer.json
- phpstan.neon
- tests/phpunit.xml
1) require PHP 7.1 or later and phpunit 7
2) test on only PHP 7.1 through 7.4
Note 1: CI currently runs `phpstan` - good stuff and it passes at the current level 0.
Note 2: there is already a config for `php-cs-fixer` but it is not running in CI. There are lots of edits that it wants to make. I will do that in a separate PR #492  because maybe nobody wants to apply such a lot of changes.
> Update dependencies and code style tools

- lib/Property/ICalendar/DateTime.php
- lib/Recur/RRuleIterator.php
- phpstan.neon
- tests/VObject/CliTest.php
- tests/VObject/ComponentTest.php
- tests/VObject/ElementListTest.php
- tests/VObject/ITip/BrokerTester.php
- tests/VObject/Recur/EventIterator/ByMonthInDailyTest.php
- tests/VObject/Recur/EventIterator/BySetPosHangTest.php
- tests/bootstrap.php
This fixes all phpstan level 1 errors and enables checking for them in CI. I'm working on a PR to also fix level 2 errors.
> Fixed phpstan level 1 errors

- .gitignore
- .travis.yml
- composer.json
These are some things I came across while working on this project. Please let me know if you have any questions
> Various infra changes

- tests/VObject/CliTest.php
Fixes #507 
To avoid:
```
There was 1 warning:
1) Sabre\VObject\CliTest::testRepair
assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.
```
e.g. https://travis-ci.org/github/sabre-io/dav/jobs/700622019 where the unit test fails in `sabre-io/dav` https://github.com/sabre-io/dav/pull/1275
> Replace assertRegExp with assertMatchesRegularExpression in unit test

- lib/Component.php
Hello,
I use the sabre/vobject library in a couple of projects. I perform static type consistency analysis using psalm on my code, which relies on the type information specified in phpdoc comments and reports inconsistencies.
I would appreciate if you could fix the type annotation included with this pull request.
> fix an incomplete phpdoc type annotation

- .travis.yml
- composer.json
- lib/ITip/Broker.php
1) sort out variables in `.travis.yml` for selecting to run php-cs-fixer, phpunit and phpstan
2) Add a matrix entry to run just phpunit on Ubuntu 20.04 "focal" with "nightly" PHP (which is the way to get PHP 8.0 at the moment)
3) When not running php-cs-fixer, explicitly remove it from `composer.json` (because php-cs-fixer does not yet support PHP 8.0, so composer cannot sort out dependencies if we have PHP 8.0 and php-cs-fixer 2.* together)
4) Fixup calendar parameter to Broker parseEvent
> Test with PHP8.0

- .travis.yml
- composer.json
- lib/timezonedata/php-bc.php
Fixes #518 and #520 
1) `US/Pacific-New` is an obsolete timezone from back in 1992 that has now been removed from the upstream timezone databases.
2) Travis now has composer major version 2.0. That complains if you do `composer remove` when there is no `composer.lock` file. Change `.travis.yml` so it does `composer remove --no-update`
3) Since composer v2.0 or some other related dependencies, "something happened" (tm) with older versions of `php-cs-fixer`. You get this sort of result:
```
$ if [ $RUN_PHPCSFIXER == "TRUE" ]; then php vendor/bin/php-cs-fixer fix --dry-run --diff; fi
In ToolInfo.php line 50:
Undefined index: name  
The command "if [ $RUN_PHPCSFIXER == "TRUE" ]; then php vendor/bin/php-cs-fixer fix --dry-run --diff; fi" exited with 1.
```
Actually in Travis jobs that have …
> Remove US/Pacific-New obsolete timezone

- CHANGELOG.md
- lib/Version.php
Note: this release removes an ancient (1992) and "never used" timezone that has been deprecated upstream for ages and has now been removed upstream in the "standard" timezone database, and in PHP's list of known timezones. There really should be absolutely nobody using it. So I am making this just a patch release because it fixes this for people who are updating to the latest PHP `7.*.*` patch releases, and the "backward-compatibility break" is so minor.
> Release 4.3.3

- composer.json
- lib/Recur/RRuleIterator.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/Recur/RRuleIteratorTest.php
- tests/phpunit.xml
As the current date is immutable every modification needs a reassignment. If you use the following rrule, then the wile loop never ends because we always test with the same date and not the modified one.
RRule to test:
`FREQ=YEARLY;COUNT=7;WKST=MO;BYDAY=MO;BYWEEKNO=13,15,50`
> Reassign modified date in yearly rrule

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Hello there,
I've felt the need of this PR becauase of a buggy event:
FREQ=MONTHLY;
INTERVAL=1;
BYMONTHDAY=2;
BYDAY=2WE;
WKST=WE;
UNTIL=20211214T000000Z
The "Until" was not being taken into account, so it was falling into the 10000 year problem.
> Make use of until parameter in nextMonthly function

- lib/Component.php
- tests/VObject/ComponentTest.php
Setting properties that are part of a group is broken since version 4.0.0. The `Component::remove()` method for the specific case of a property given by its name (as string) that includes a group prefix will throw an exception. However, I believe the exception is only intended for the usage of this function where the property to remove is given as an object reference, not as a string, where the given property/component is not a child of component the remove() method is called on.
Example code to trigger the exception:
```php
<?php
use Sabre\VObject;
use Sabre\VObject\Component\VCard;
include_once dirname(__FILE__) . "/vendor/autoload.php";
$vcard = new VObject\Component\VCard([
'VERSION' => '3.0',
'item2.X-ABLabel' => "Foo", // triggers exception
]);
$vcard->{"item1.X-ABLabel"} = …
```
> Fix setting properties with group assignment

- CHANGELOG.md
- lib/Version.php
I should have done these things before releasing 4.3.6:
1) bump the VERSION constant
2) add the changelog details to CHANGELOG.md
This PR commits the changes (but too late for 4.3.6). There are some other PRs to be finished, so I can do a 4.3.7 release very soon and do the process better for that.
> Changes that should have happened for 4.3.6

- lib/ITip/Broker.php
- tests/VObject/ITip/BrokerSignificantChangesTest.php
https://github.com/sabre-io/vobject/issues/540
If a server (using sabre) receives a VEVENT update it will send mails to all attendees. Not for all modified events, but for events with a "significant change". The calculation of "signifcant change" is done by vobject.
I have trouble with to many "Invitation: ..."-Mails for events that has not been changed.
Investigating this I have seen:
- the events were modified by the client and sent to the server (eg. to save the acknowledgment of an alarm).
- the client has changed the order (not the attendees itself) of the attendees in the modified event
- vobject calculated a "significant change"
- the server sent the email
I think everything is correct, except, the reordering is not a significant change. Why the client desires to reorder the …
> Reordering of the attendees should not be a signitifcant change (#540)

- lib/ITip/Broker.php
- tests/VObject/ITip/BrokerSignificantChangesTest.php
Related to #540
If a server (using sabre) receives a VEVENT update it will send mails to all attendees. Not for all modified events, but for events with a "significant change". The calculation of "signifcant change" is done by vobject.
I have trouble with to many "Invitation: ..."-Mails for events that has not been changed.
Investigating this I have seen:
- the events were modified by the client and sent to the server (eg. to save the acknowledgment of an alarm).
-  the client has changed the order (not the vevents itself) of the venets in the modified event
-  vobject calculated a "significant change" (by SignificantChangeHash)
-  the server sent the email
I think everything is correct, except, the reordering is not a significant change. Why the client desires to reorder the vevents? I …
> Reordering of vevent should not be a significant change (#542)

- lib/TimeZoneUtil.php
- lib/TimezoneGuesser/FindFromOffset.php
- lib/TimezoneGuesser/FindFromTimezoneIdentifier.php
- lib/TimezoneGuesser/FindFromTimezoneMap.php
- lib/TimezoneGuesser/GuessFromLicEntry.php
- lib/TimezoneGuesser/GuessFromMsTzId.php
- lib/TimezoneGuesser/TimezoneFinder.php
- lib/TimezoneGuesser/TimezoneGuesser.php
- tests/VObject/TimeZoneUtilTest.php
This will ease customization of timezone-guessing as it is now gets easier to extend that process with own implementations (as long as they implement the appropriate interface)
This is espechially necessary when wanting to actually guess a timezone via the rules defined in the VTIMEZONE-entry (which is currently not done)
This change does not introduce any new logic. It just rearranges the already existing code in a different way to allow creating own TimezoneGuessers that can extend the functionality like this:
```php
class BuesingenGuesser implements TimezoneGuesser
{
public function guess(VTimeZone $vtimezone, bool $throwWhenUnsure = false): ?DateTimeZone
{
return new DateTimeZone('Europe/Busingen');
}
}
TimezoneUtil::addTimeZoneGuesser(new BuesingenGuesser());
```
Now every time a …
> Allow easier extension of the timezone guessing

- CHANGELOG.md
- lib/Version.php
PR #548 add new flexibility for extending the timezone guessing, so that new flexibility should be a minor version bump.
This is the changelog and version bump in preparation for a release.
> Changelog for 4.4.0

- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Property/Binary.php
- lib/Property/FloatValue.php
- lib/Property/ICalendar/CalAddress.php
- lib/Property/ICalendar/Duration.php
- lib/Property/ICalendar/Period.php
- lib/Property/Time.php
- lib/Property/Uri.php
- lib/Property/UtcOffset.php
- lib/Property/VCard/DateAndOrTime.php
- lib/Property/VCard/TimeStamp.php
- lib/Recur/EventIterator.php
- lib/Recur/RDateIterator.php
- lib/Recur/RRuleIterator.php
Related to https://github.com/sabre-io/vobject/issues/556
> Fix deprecations warnings on PHP 8.1

- lib/Component.php
I recently set up Baïkal, and it works wonderfully with most clients I let at it. However, I ran into an issue when I tried using InfCloud pointed at it: my address book didn't display, because Baïkal returned a HTTP 500 to some request InfCloud was making.
I dug into the logs, and I found that the issue is this backtrace:
```
today at 1:58:13 AM2022/05/11 23:58:13 [error] 23#23: *1387 FastCGI sent in stderr: "PHP message: ErrorException: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/baikal/vendor/sabre/vobject/lib/Component.php:252
today at 1:58:13 AMStack trace:
today at 1:58:13 AM#0 [internal function]: Baikal\Framework::exception_error_handler()
today at 1:58:13 AM#1 /var/www/baikal/vendor/sabre/vobject/lib/Component.php(252): …
```
> Component/select: Before uppercasing $child->group, make sure it isn't null

- lib/Property/ICalendar/CalAddress.php
- tests/VObject/Property/ICalendar/CalAddressTest.php
so far getNormalizedValue() only lowercased schema-value.
for mailto:-addresses it now lowercases the address as well.
> lowercase mailto:-addresses in getNormalizedValue()

- lib/Component/VCard.php
- tests/VObject/Component/VCardTest.php
This is a rare yet possible case (I stumbled upon such VCards in my own Google Account storage) where a NICKNAME is defined on a VCard but no FN. Importing such contacts into Nextcloud (using Sabre/VObject) is a bit of a pain, this attempts to solve it.
> Add NICKNAME fallback for VCards without FNs

- lib/Parser/MimeDir.php
- tests/VObject/Parser/MimeDirTest.php
Sometimes it seems like parameters can be added multiple times with the same value. Besides not making any sense (and partially being not allowed in the first place) this will also possibly break the further process of parsing an icalendar file.
This modification adds a shortcut when the last parameter-value and the current parameter value are exactly the same. In that case the new value is ignored and only the old value will be used.
The use-case - as documented in the test - is that there seem to be icalendar files that contain the following content:
DTSTART;VALUE=DATE;VALUE=DATE:20220612
While that seems to violate the RFC it is not seen as a violation in the icalendar validator at https://icalendar.org/validator.html and as it can also be imported by other calendaring systems it looks …
> Ignore multiple same parameter-values

- lib/Parser/MimeDir.php
- tests/VObject/Parser/MimeDirTest.php
Previously when OPTION_IGNORE_INVALID_LINES was set any invalid content of a property was ignored.
With this change now also invalid properties themselves are ignored.
This will help importing feeds that contain broken multi-line contents where newlines are not propperly escaped and therefore parts of the multiline content show up as property themselves. Without this addition the import will then break and not import anything at all. With this change added an import will now succeed when invalid lines shall be ignored.
Without the option set everything will behave as before.
> Fully ignore invalid lines

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Consider the rrule:
`FREQ=YEARLY;BYMONTH=5;BYSETPOS=3;BYMONTHDAY=3`
It will not generate any occurrence, but the `RRuleIterator` will stuck in the infinite loop
> Fix infinite loop caused by yearly with bySetPos

- lib/Parser/MimeDir.php
- tests/VObject/ReaderTest.php
There are cases when objects do not have closing tags (for example, END: VCALENDAR), this fix solves this issue.
> Handle Vobjects without closing tag

- tests/VObject/Parser/MimeDirTest.php
- tests/VObject/Recur/EventIterator/MainTest.php
It looks like a new version of php-cs-fixer likes having a bit more spacing in PHPdoc blocks.
Apply these changes so that CI will be green.
> Fix code-style

- .github/workflows/ci.yml
PHP 8.2 is available now in GitHub, and it passes.
> Add PHP 8.2 to CI

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/Parser/MimeDir.php
- lib/Version.php
- tests/VObject/StringUtilTest.php
Apply "Remove utf8_encode" to 4.5 so that we can make a simple 4.5.1 release, without all the arg/return-type changes that are in progress on master.
And add PHP 8.2 to the CI here, to demonstrate that it passes.
> Remove utf8_encode

- CHANGELOG.md
- lib/Version.php
4.5.1 was already released on the 4.5 branch. The actual code fix is already in the master branch (as well as the 4t into master=.5 branch). Only the version change and changelog need to be brought into master.
> Prepare 4.5.1

- composer.json
I would like to use sabre/vobject together with latest sabre/xml v4.
Latest vobject release still uses sabre/xml v2.
> Support sabre/xml v4

- .github/workflows/ci.yml
- lib/Component.php
- lib/Parser/MimeDir.php
Will fix warnings in ci
https://github.com/sabre-io/vobject/actions/runs/3986493156
checkout@v3
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/cache@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
set-output
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Codecov (needs testing)
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1
> chore: fix ci deprecations

- lib/ITip/Broker.php
The type definition for oldCalendar is fixed on master.
I would be happy about a back port for 4.5 to reduce the false-positive warnings by static code analysis.
> docs: fix type definition for oldCalendar

- .github/dependabot.yml
Currently there is no package manager or similar for GH Actions to manage the dependencies.
Dependabot offers to monitor the workflow scripts and propose new versions as PR.
Since GH Actions rarely change and no resources should be wasted, a repetition of one month is sufficient.
Automates chore like  #608
> Add dependabot to create GH action version update PRs

- composer.json
Recent php-cs-fixer minor releases suggest some new things.
For example, see PR https://github.com/sabre-io/xml/pull/271
It passes here in https://github.com/sabre-io/vobject so no code needs to be touched, but I may as well bump the required php-cs-fixer version to match with other repos.
> chore: use php-cs-fixer 3.49

- composer.json
After PR #644 adjusted the code indent, we need to use at least php-cs-fixer 3.54
May as well record that in `composer.json` - I forgot to do that yesterday.
> chore: bump php-cs-fixer requirement to 3.54

- lib/Document.php
- lib/Parser/MimeDir.php
- lib/Property.php
- tests/VObject/Component/VCalendarTest.php
add `lineIndex` and `lineString` properties to a `Property` Node
issue #646
> fix issue #646

- lib/ITip/Broker.php
- tests/VObject/ITip/BrokerProcessReplyTest.php
fixes #358, closes #360
While rebasing #360, I noticed that it only fixes replies to new exception events. I use a different approach now, which also fixes replies to existing exception events.
> ITip\Broker: handle timezones in replies to exception events

- lib/Parser/MimeDir.php
- tests/VObject/Parser/MimeDirTest.php
Issue #657 
`parse` can be called with input `null`, but the caller should have previously provided an input stream that is already set up.
The change in this PR makes `parse` throw a `ParseException` if it is called the first time with `null`
This should help anyone calling this, or `Reader::read()` with no input. Instead of getting a PHP Fatal error, they will get an exception.
> throw ParseException when null input is provided

- .gitattributes
- .github/workflows/ci.yml
- lib/Document.php
- lib/ITip/Broker.php
- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Recur/RRuleIterator.php
- phpstan.neon
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/ITip/BrokerProcessReplyTest.php
- tests/VObject/Parser/MimeDirTest.php
- tests/VObject/Recur/RRuleIteratorTest.php
Backport changes from master that have happened since release https://github.com/sabre-io/vobject/releases/tag/4.5.4 on 2023-11-09
These come from PRs
#632 Add PHP 8.3 to CI
#637 Bump GitHub workflow actions/cache to 4
#638 Bump codecov/codecov-action to 4
#649 add lineIndex and lineString properties to a Property Node
#652 ITip\Broker: handle timezones in replies to exception events
#654 chore: stop exporting php-cs-fixer config
#656 Yearly rrule compliance by the iterator
#658 throw ParseException when null input is provided
I had to remove some code like `?int` that does not work on PHP 7.1 (just declare the parameter `int`). But everything seems to work right back to PHP 7.1, and all tests pass.
This keeps the 4.5 branch up-to-date with fixes/changes that are pending release.
> Backport from master branch

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Issue #648 
1st commit is the test code added by @schreven in PR #647 
2nd commit is my first code that makes those test cases pass. It only touches the case of events that recur at an interval of days.
- added more test cases for weekly, monthly and yearly recurring events, that are engineered so that some event recurrence fall in the 0200 to 0300 summer time start on the exact day that summer time does start.
- adjusted code to make those pass (similar to what I did for the daily case)
- refactored to avoid the repeated code pattern
- added tests and adjusted code for `nextHourly`
Thanks to @gharlan and @schreven for input, code suggestions etc.
> Handle summer time jumps in event recurrences

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Backport #653 to 4.5 release branch
ToDo:
> [4.5] Handle summer time jumps in event recurrences

- lib/Component/VTodo.php
- tests/VObject/Component/VTodoTest.php
This PR should fix the linked issue I created about the `PERCENT-COMPLETE` property of the `VTODO` being misspelled as just `PERCENT`. I also added a test to verify that the validation of the property now works as expected. If you think the test is unnecessary, I can also just remove it again.
Fixes #663
> Fix VTODO validation for PERCENT-COMPLETE

- tests/VObject/Component/VTodoTest.php
Follow-on from #664 
Tests that a now-unknown property called "PERCENT" is still accepted in a VTODO.
> test: extra property is allowed in VTODO

- bin/bench.php
- bin/bench_freebusygenerator.php
- bin/bench_manipulatevcard.php
- bin/rrulebench.php
- composer.json
- tests/VObject/ITip/BrokerDeleteEventTest.php
The latest php-cs-fixer and phpstan want to make a few changes.
I needed to pin php-cs-fixer to 3.62.0 because of issue https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8182
After that is fixed, we can probably move to 3.63
> chore: adjust code to make php-cs-fixer and phpstan pass

- lib/Component/VAlarm.php
- tests/VObject/Component/VAlarmTest.php
Following RFC 5545 (https://www.rfc-editor.org/rfc/rfc5545#page-74) the start of a VTODO is DTSTART not DUE
Fixing the tests in consequence
> Fix Alarm related to DTSTART of VTODO

- composer.json
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.63.2 has been released.
That fixed https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8182
So now we are fine to use the php-cs-fixer 3.63 series.
> chore: use php-cs-fixer 3.63

- tests/VObject/Issue153Test.php
- tests/VObject/Issue64Test.php
> refactor: Replace dirname(__FILE__) with __DIR__

- tests/VObject/Issue153Test.php
- tests/VObject/Issue64Test.php
Backport #675 from master, just to keep the test code as much in sync as possible.
> [4.5] refactor: Replace dirname(__FILE__) with __DIR__

- lib/Component/VCalendar.php
- lib/DateTimeParser.php
- lib/Document.php
- lib/FreeBusyGenerator.php
- lib/ITip/Broker.php
- lib/Property.php
- lib/Property/ICalendar/DateTime.php
- lib/Recur/EventIterator.php
- lib/TimeZoneUtil.php
This fixes deprecation warnings triggered in PHP 8.4.
> Fix `Implicitly marking parameter $param as nullable is deprecated`

- lib/Property/ICalendar/Recur.php
- tests/VObject/Property/ICalendar/RecurTest.php
Backport #692 to 4.5 branch
In master, `use Sabre\VObject\InvalidDataException;` is already there, because various declarations of things, parameter types, return types etc have been added in master. I had to add the `use` statement in the backport.
> [4.5] Throw InvalidDataException when RRule is invalid

- CHANGELOG.md
- lib/Version.php
There have been various patch releases in the 4.5.x series from the 4.5 branch.
This PR forward-ports the change logs, and bumps the version in master.
Note: `master` currently has partly-completed code to improve code analysis by adding type declarations and PHPdoc improvements. There has not been any recent release from `master` - that will happen "some day"
> chore: forward port 4.5.6

- lib/Document.php
- tests/VObject/PropertyTest.php
Currently value-types that are not known will cause the parser to throw an InvalidDataException. In [RFC5545, Section 3.2.20](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.20) is described though that the allowed values for the "VALUE" data-type can include x-names and iana-tokens. These can be any string that might - or might not - be understood by the parser. The description clearly states that "Applications MUST preserve the value data for x-name and iana-token value that they don't recognize without attempting to interpret or parse the value data"
This means that the content of the "VALUE" part should not be interpreted at all the moment the parser doesn't find a match in the corresponding mapping table.
But it should also not hard-fail when someone sets a VALUE that might …
> Allow unknown value data types for VALUE

- lib/Document.php
- tests/VObject/PropertyTest.php
Backport PR #674 to 4.5 branch
> Allow unknown value data types [4.5]

- composer.json
- lib/Component/VCalendar.php
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.65.0 was released last week.
It finds just one minor thing to change in the source code. Apply that change so that CI will pass.
> chore: bump php-cs-fixer to 3.65

- composer.json
Backport of #705 to the 4.5 branch.
> chore(deps): allow phpstan major version 2 [4.5]

- lib/ElementList.php
- lib/Node.php
- lib/Property.php
- lib/Property/ICalendar/DateTime.php
See #563.
This adds only phpdoc return types as real return types would not work for the earlier php versions this library supports.
> add phpdoc return types for arrayaccess methods (fixes #563)

- lib/timezonedata/exchangezones.php
Add new timezone in lib/timezonedata/exchangezones.php:
'Amsterdam, Berlin, Bern, Rom, Stockholm, Wien' => 'Europe/Berlin', 
Example ICS-File:
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:***
BEGIN:VTIMEZONE
TZID:(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
.....
> Add new exchangetimezone 'Amsterdam, Berlin, Bern, Rom, Stockholm, Wien'

- lib/timezonedata/exchangezones.php
'Amsterdam, Berlin, Bern, Rom, Stockholm, Wien' => 'Europe/Berlin',
Backport of #618
> [4.5] Add timezone Europe/Berlin
