- bin/fetch_windows_zones.php
- bin/generate_vcards
Fixes https://github.com/fruux/sabre-vobject/issues/194
> Fixed short array syntax for PHP < 5.4

- composer.json
@Hywan are you ok with this change?
> Adding ivan to developer list.

- lib/Property/VCard/Date.php
- tests/VObject/Property/VCard/DateAndOrTimeTest.php
> Fix Property\VCard\Date to serialize DateTime objects as date-only string

- lib/Component/VEvent.php
- tests/VObject/Component/VEventTest.php
> vEvent->isInTimeRange() fails for all-day events that end on start of given time range 

- CHANGELOG.md
- lib/Component/VEvent.php
- tests/VObject/Component/VEventTest.php
> Handling NoInstancesException in isInTimeRange()

- tests/VObject/IssueUndefinedIndexTest.php
Rebased version of #222 to master.
> Test for undefined index issue

- CHANGELOG.md
- lib/Recur/EventIterator.php
- lib/Recur/MaxInstancesExceededException.php
- tests/VObject/Recur/EventIterator/MaxInstancesTest.php
> Automatically stop recurring after 3500 iterations.

- CHANGELOG.md
- lib/FreeBusyGenerator.php
- lib/Recur/EventIterator.php
- lib/Settings.php
- tests/VObject/Recur/EventIterator/MaxInstancesTest.php
> Moved $maxInstances to Settings::$maxRecurrences.

- CHANGELOG.md
- lib/Component/VCard.php
- tests/VObject/Component/VCardTest.php
- tests/VObject/Issue40Test.php
- tests/VObject/Property/BinaryTest.php
> Making vCard version 4 the default

- lib/Property/VCard/DateAndOrTime.php
- tests/VObject/CliTest.php
- tests/VObject/ITip/BrokerAttendeeReplyTest.php
Remove some of the variables and assignments that are not needed. More changes might come in another pull request.
> Remove some useless variables and assignments

- .travis.yml
- lib/Component/VCalendar.php
- lib/Component/VCard.php
- lib/Property/FloatValue.php
- lib/Property/IntegerValue.php
- tests/VObject/Property/FloatTest.php
@evert this will bring php7 to vobject 3.4 - no idea if the class rename is valid in terms of api breackage - worth a 3.5???
> PHP 7 support for vobject 3.4

- lib/Component/VCalendar.php
- tests/VObject/Component/VCalendarTest.php
> Fix issue 290: fix vcalendar#getBaseComponent filter feature

- lib/Parser/MimeDir.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/ITip/BrokerDeleteEventTest.php
- tests/VObject/Parser/MimeDirTest.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/EventIterator/MaxInstancesTest.php
- tests/VObject/Recur/RDateIteratorTest.php
Delete unused variables, fix function names
> Some style fixes

- lib/Parser/MimeDir.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/ITip/BrokerDeleteEventTest.php
- tests/VObject/Parser/MimeDirTest.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/EventIterator/MaxInstancesTest.php
- tests/VObject/Recur/RDateIteratorTest.php
Reverts fruux/sabre-vobject#296
> Revert "Some style fixes"

- tests/VObject/Component/VCalendarTest.php
- tests/VObject/ITip/BrokerDeleteEventTest.php
- tests/VObject/Parser/MimeDirTest.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/EventIterator/MaxInstancesTest.php
- tests/VObject/Recur/RDateIteratorTest.php
- Uppercase VObject properties
- fix function names
- remove unused variables
> Fix some coding issues in tests

- lib/Component/VCard.php
- tests/VObject/Component/VCardTest.php
Hello! I had a requirement for this feature so I thought I would create a PR to discuss.
> [RFC] add VCard::getByType()

- lib/Property/ICalendar/Recur.php
- tests/VObject/Property/ICalendar/RecurTest.php
> Issue 303 - Use number instead of string for COUNT property in RRULE

- ChangeLog.md
- lib/ITip/Broker.php
- tests/VObject/ITip/BrokerProcessReplyTest.php
Hi @Michael-Gusev, @vkomrakov-sugar 
I added a simple change in #309 to help with solving your recurrence issue. This is already merged. In this PR I created a simpler version of the test you created in #308. It looks to me like the problem is now fixed.
Let me know if #309 and this solves the problem for you as well. If not, we'll dig deeper :)
Fixes #306.
Closes #308.
> Added test case for #306.

- lib/Recur/EventIterator.php
- tests/VObject/Recur/EventIterator/SameDateForRecurringEventsTest.php
New PR, this time with the correct branch.
> Fix for #330 for 3.5 branch

- lib/Property.php
- lib/Property/ICalendar/Recur.php
- tests/VObject/PropertyTest.php
Level 1 is only allowed if REPAIR is on (see Node.php#L153)
> Fixed some validate() warning levels

- lib/Property/ICalendar/Recur.php
- lib/Recur/RRuleIterator.php
- tests/VObject/Property/ICalendar/RecurTest.php
- tests/VObject/Recur/RRuleIteratorTest.php
- added basic validation rules for RRULE BYYEARDAY in RRuleIterator
- added code to use BYYEARDAY in calculation for next occurrence
- added validation checks for BYYEARDAY in Recur->validate()
> RRULE BYYEARDAY implementation for issue #340

- CHANGELOG.md
- lib/Version.php
> Updated changelog, bumped version

- lib/Parser/MimeDir.php
- tests/VObject/Parser/MimeDirTest.php
> Support case-insensitive CHARSET Property for vCard 2.1

- lib/Property.php
- lib/Property/Text.php
This is a comparison of a CardDAV call in my application, requesting 22 contacts:
> Serialization: Performance boost for long properties

- lib/Property.php
- lib/Property/Text.php
we see blackfire profiles where this path is very very hot:
> move a single strlen() function call from the hot path

- lib/Component/VEvent.php
- lib/Component/VJournal.php
DTSTAMP must be specified in UTC
See https://www.kanzaki.com/docs/ical/dtstamp.html
> DTSTAMP must be specified in UTC

- lib/Recur/RRuleIterator.php
- tests/VObject/Recur/RRuleIteratorTest.php
Fixed #442 
Just before the RRuleIterator hits the year 10.000 we stop iterating.
> we stop before the year 10000

- lib/Recur/RRuleIterator.php
> respect operator precedence

- CHANGELOG.md
- lib/Version.php
Closes https://github.com/sabre-io/vobject/issues/478
> Release 4.2.1

- .gitignore
- .travis.yml
- lib/Cli.php
- lib/Component.php
- lib/Component/VEvent.php
- lib/PHPUnitAssertions.php
- lib/Parser/MimeDir.php
- lib/Parser/XML/Element/KeyValue.php
- lib/Property/Boolean.php
- lib/Property/IntegerValue.php
- lib/Property/Text.php
- lib/Property/Uri.php
- lib/Recur/NoInstancesException.php
- lib/Recur/RRuleIterator.php
- lib/Settings.php
- lib/TimeZoneUtil.php
- lib/VCardConverter.php
- Bump phpstan in CI to 0.12.5
- ignore `.idea` (PHPstorm) so I and others do not accidentally commit it
- fix various typos (all expect 1 are just in comments, 1 is in an error message)
> Latest phpstan 0.12.5

- .travis.yml
- composer.json
- tests/phpunit.xml
Like done recently in `skel` and the other `sabre-io` repos.
> Standardize CI

- CHANGELOG.md
- lib/Version.php
Bump patch version to 4.3.1 and add changelog.
Issue #509
> Release 4.3.1

- lib/Recur/EventIterator.php
- tests/VObject/Recur/EventIterator/OverrideDurationTest.php
> EventIterator returns wrong endTime (#534)

- lib/StringUtil.php
Also get rid of deprecated utf8_encode
Spin-off of sabre-io/http#182
> Fix encoding detection on PHP 8.1

- CHANGELOG.md
- bin/generate_vcards
- bin/mergeduplicates.php
- bin/vobject
- lib/Document.php
- lib/Parser/Json.php
- lib/Parser/MimeDir.php
- lib/Property.php
- lib/Property/Boolean.php
- lib/Property/FlatText.php
- lib/Property/FloatValue.php
- lib/Property/IntegerValue.php
- lib/Property/Text.php
- lib/Property/Time.php
- lib/Property/Uri.php
- lib/Splitter/ICalendar.php
- lib/TimezoneGuesser/FindFromTimezoneIdentifier.php
- lib/VCardConverter.php
- lib/timezonedata/lotuszones.php
- tests/VObject/Component/VTodoTest.php
- tests/VObject/FreeBusyGeneratorTest.php
- tests/VObject/Recur/EventIterator/HandleRDateExpandTest.php
- tests/VObject/Recur/EventIterator/IncorrectExpandTest.php
- tests/VObject/Recur/EventIterator/InfiniteLoopProblemTest.php
to reduce the amount that my IDE keeps telling me about while I code.
This is all just in comments and tests - nothing functional.
> Adjust some grammar

- lib/Parser/MimeDir.php
- tests/VObject/StringUtilTest.php
Fixes #596 
Use explicit calls to `mb_convert_encoding`
> Remove utf8_encode

- lib/BirthdayCalendarGenerator.php
- lib/Component.php
- lib/Component/VAvailability.php
- lib/Component/VCalendar.php
- lib/Component/VCard.php
- lib/Component/VTodo.php
- lib/DateTimeParser.php
- lib/Document.php
- lib/ElementList.php
- lib/FreeBusyGenerator.php
- lib/ITip/Broker.php
- lib/Node.php
- lib/Parser/MimeDir.php
- lib/Parser/Parser.php
- lib/Parser/XML.php
- lib/Property.php
- lib/Property/ICalendar/DateTime.php
- lib/Property/Uri.php
- lib/Property/VCard/DateAndOrTime.php
- lib/Recur/EventIterator.php
- lib/Recur/MaxInstancesExceededException.php
- lib/Recur/NoInstancesException.php
- lib/Recur/RRuleIterator.php
- lib/TimeZoneUtil.php
- lib/TimezoneGuesser/FindFromTimezoneIdentifier.php
- tests/VObject/Component/VCalendarTest.php
- tests/VObject/Component/VCardTest.php
- tests/VObject/FreeBusyGeneratorTest.php
The latest cs-fixer wants to do this.
I looked through the diffs, and it seems OK to me.
> Apply cs-fixer changes

- .github/workflows/ci.yml
- composer.json
- lib/Component/VCard.php
- lib/Node.php
- lib/Parser/MimeDir.php
- lib/Property/VCard/DateAndOrTime.php
- lib/Recur/EventIterator.php
so that CI will pass.
I needed to let cs-fixer update some code comments and formatting so that the current version 3.38.0 will pass.
> Update CI stuff

- CHANGELOG.md
- lib/Version.php
let's get these little things released as a patch in the current 4.5 series.
> Prepare 4.5.4

- composer.json
- lib/Component/VCalendar.php
- lib/VCardConverter.php
Apply small changes suggested by cs-fixer 3.51
> chore: use php-cs-fixer 3.51

- CHANGELOG.md
- lib/Version.php
IMO these can all be called "patches" or "bugfixes". So just incrementing the patch number is fine.
> prepare release 4.5.5

- README.md
> docs: Remove outdated build status in README.md

- .github/workflows/ci.yml
- .php-cs-fixer.dist.php
- composer.json
similar CI changes to what has been done in other sabre repos.
> chore: add PHP 8.4 to CI of master
